#!/bin/sh  
  
mysql_port=3308  
mysql_username=root  
mysql_password=password 
mysqld_safe_sh=/usr/local/mysql/bin/mysqld_safe
mysqladmin_sh=/usr/local/mysql/bin/mysqladmin
default_file=/var/databases/conf/my.cnf  
mysql_sock=/var/databases/mysql/mysqld.sock

function_start_mysql()  
{  
    printf "Starting MySQL...\n"  
    /bin/sh $mysqld_safe_sh --defaults-file=$default_file 2>&1 > /dev/null &  
}  
  
function_stop_mysql()  
{  
    printf "Stoping MySQL...\n"  
    $mysqladmin_sh -u ${mysql_username} -p${mysql_password} -S $mysql_sock shutdown  
}  
  
function_restart_mysql()  
{  
    printf "Restarting MySQL...\n"  
    function_stop_mysql  
    sleep 5  
    function_start_mysql  
}  
  
function_kill_mysql()  
{  
    kill -9 $(ps -ef | grep 'bin/mysqld_safe' | grep ${mysql_port} | awk '{printf $2}')  
    kill -9 $(ps -ef | grep 'libexec/mysqld' | grep ${mysql_port} | awk '{printf $2}')  
}  
  
if [ "$1" = "start" ]; then  
    function_start_mysql  
elif [ "$1" = "stop" ]; then  
    function_stop_mysql  
elif [ "$1" = "restart" ]; then  
function_restart_mysql  
elif [ "$1" = "kill" ]; then  
function_kill_mysql  
else  
    printf "Usage: /etc/init.d/mysql {start|stop|restart|kill}\n"  
fi